[general]
use_daemon = "awww"
default_path = "/tmp"

[awww]
filter = "Lanczos3"
transition_type = "simple"
transition_step = 90
transition_duration = 3
transition_fps = 60
transition_angle = 45
transition_pos = "center"
transition_bezier = "0.54,0,0.34,0.99"
transition_wave = "20,20"

[client]
wallhaven_api = "api_key"

[wallhaven]
# query filters the search that matches query
query = ""
# categories filters search
# "general:100", "anime:010", "people:001"
categories = "010"
# purity filters content rating
# "sfw:100", "sketchy:010", "nsfw:001"
# nsfw rating needs a valid api_key
purity = "110"
# sorting filters how the wallpapers are sorted
# "date_added", "relevance", "random", "views", "favorites", "toplist"
sorting = "random"
# order filters how wallpaper appear in order
# "desc" and "asc"
order = "desc"
# at_least filters the minimum resolution of wallpapers to be fetched
# accepts only one value in "WIDTHxHEIGHT"
at_least = "1920x1080"
# ratios filters the fetched wallpapers to a list of acceptable aspect ratios
# accepts a list separated by commas: "16x9,16x10..."
ratios = "16x9"
# seed specifies the randomness acceping alphanumeric values
# only if sorting is set to "random"
seed = "hdks23"
